# Generated by Django 4.2.5 on 2023-09-17 10:17

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0002_alter_taskitem_assigned_users_alter_taskitem_prio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskitem',
            name='author',
            field=models.ForeignKey(default=django.contrib.auth.models.AbstractUser.get_full_name, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
